# Hugo Config for blog.ethanrjones.name
baseURL = 'https://blog.ethanrjones.name'
languageCode = 'en-us'

# Personalize website names and headers.
title = 'Bits and Bytes'
subtitle = "A Tech Blog by Ethan R. Jones, Linux Nerd."
author = "Ethan R. Jones"

# Customize post button names.
menuMore = "Show More"
readMore = "Read More"
readOtherPosts = "Read Other Posts"
newerPosts = "Newer Posts"
olderPosts = "Older Posts"
missingContentMessage = "404 - Page Not Found..."
missingBackButtonLabel = "Back to home page"

# Allow :: codes for emoji in posts.
enableEmoji = true

#Enable a robots.txt for Google bot. 
enableRobotsTXT = true

# Choose Theme
theme = "hugo-bearblog"

[menu]
  [[menu.main]]
    identifier = "me"
    name = "Me"
    url = "https://ethanrjones.name/"
    weight = 0

[params]
  themeColor = "pink"
  favicon = "favicon.webp"
  mainSections = ["posts"]
  # OpenGraph related bits.
  title = "Bits and Bytes"
  description = "A Tech Blog by Ethan R. Jones, Linux Nerd."
  # image = ["static/share.jpg"] # TODO - need a good OpenGraph image...

  # Will show git related data.
  showLastUpdated = true

  showLanguageSelector = false
  centerTheme = true
  readingTime = true
